class ManageError(Exception):
    def __init__(self,message):
        self.message=message
        super().__init__(self.message)
class InvalidDate(ManageError):...
class InvalidPrice(ManageError):...
class InvalidStock(ManageError):...
class InvalidWarranty(ManageError):...